name: Python package in docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: build & package in docker
        run: |
          sudo docker build -t my-python-app-tmp . --file Dockerfile
      - name: run it and copy the package and destroy images
        run: |
          sudo docker run  -d  --name my-python-app-tmp my-python-app-tmp
          sudo docker cp my-python-app-tmp:/root/bin.tgz  /mnt/smb/
          sudo docker rm -f my-python-app-tmp
          sudo docker rmi my-python-app-tmp